### ISSUE TITLE
InViewport() method broken

### ISSUE THREAD

**Issue by chidifrank** [powbot/api#2] opened 2020-10-10 16:19 UTC
inViewport() method returns false when the npc is in our viewport.
https://i.gyazo.com/d3ab880f9abd74bcbc3aebac837912cc.mp4

**Comment by iDznPB** [comment] 2020-10-10 18:03
I've tested this and for me, it only seems to be for npc's, I've used both rocks and trees to use for objects which returns fine but npc's it always returns false.

**Comment by constt** [comment] 2020-10-11 06:35
Unable to reproduce, I've made some changes which might help. Please try latest and let me know.

**Comment by constt** [comment] 2020-10-11 07:06
Might be fixed by https://github.com/powbot/api/pull/6/commits/79f2350a4aede7463e195831b2964c53d91c1169

**Comment by k0na** [comment] 2020-10-11 09:10
@constt using anything but `centerPoint` for `inViewport` for npcs will cause issues (false positives), unless model animations have been implemented.

**Comment by RZME** [comment] 2020-10-11 11:26
@constt certain interactive GameObjects are still not being recognized

**Comment by constt** [comment] 2020-10-11 18:00
@k0na Model animations have which makes this strange.

**Closed as completed** 2020-10-23 03:24 UTC
